<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Adapter\Alias\Repository\AliasRepository' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Adapter\\Alias\\Repository\\AliasRepository'] = new \PrestaShop\PrestaShop\Adapter\Alias\Repository\AliasRepository(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), 'ps_', new \PrestaShop\PrestaShop\Adapter\Alias\Validate\AliasValidator());
