<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\ChangePasswordType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\ChangePasswordType'] = new \PrestaShopBundle\Form\Admin\Type\ChangePasswordType(($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['translator'] ?? $this->getTranslatorService()));
