<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\CountryChoiceType' shared autowired service.

$a = ($this->services['prestashop.core.form.choice_provider.country_by_id'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_CountryByIdService.php'));

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\CountryChoiceType'] = new \PrestaShopBundle\Form\Admin\Type\CountryChoiceType($a, $a);
