<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Employee\EmployeeOptionsType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Configure\\AdvancedParameters\\Employee\\EmployeeOptionsType'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Employee\EmployeeOptionsType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.core.team.employee.configuration.options_checker'] ?? $this->load('getPrestashop_Core_Team_Employee_Configuration_OptionsCheckerService.php'))->canBeChanged());
