<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Adapter\Country\CommandHandler\EditCountryHandler' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Adapter\\Country\\CommandHandler\\EditCountryHandler'] = new \PrestaShop\PrestaShop\Adapter\Country\CommandHandler\EditCountryHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\Country\\Repository\\CountryRepository'] ?? $this->load('getCountryRepositoryService.php')));
