<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Command\FeatureFlagCommand' shared autowired service.

$this->services['PrestaShopBundle\\Command\\FeatureFlagCommand'] = $instance = new \PrestaShopBundle\Command\FeatureFlagCommand(($this->services['PrestaShopBundle\\Entity\\Repository\\FeatureFlagRepository'] ?? $this->getFeatureFlagRepositoryService()));

$instance->setName('prestashop:feature-flag');

return $instance;
