<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Import\ImportDataConfigurationType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Configure\\AdvancedParameters\\Import\\ImportDataConfigurationType'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Import\ImportDataConfigurationType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.core.form.choice_provider.import_match_configuration'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ImportMatchConfigurationService.php'))->getChoices(), ($this->services['prestashop.core.form.choice_provider.import_entity_field'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ImportEntityFieldService.php'))->getChoices());
