<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Product\ProductInformation' shared autowired service.

@trigger_error('The "PrestaShopBundle\\Form\\Admin\\Product\\ProductInformation" service is deprecated. You should stop using it, as it will be removed in the future.', E_USER_DEPRECATED);

return $this->privates['PrestaShopBundle\\Form\\Admin\\Product\\ProductInformation'] = new \PrestaShopBundle\Form\Admin\Product\ProductInformation(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService()), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')), ($this->services['prestashop.adapter.data_provider.category'] ?? $this->load('getPrestashop_Adapter_DataProvider_CategoryService.php')), ($this->services['prestashop.adapter.data_provider.product'] ?? $this->load('getPrestashop_Adapter_DataProvider_ProductService.php')), ($this->services['prestashop.adapter.data_provider.feature'] ?? $this->load('getPrestashop_Adapter_DataProvider_FeatureService.php')), ($this->services['prestashop.adapter.data_provider.manufacturer'] ?? ($this->services['prestashop.adapter.data_provider.manufacturer'] = new \PrestaShop\PrestaShop\Adapter\Manufacturer\ManufacturerDataProvider())));
