<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.definition.factory.customer' shared service.

$this->services['prestashop.core.grid.definition.factory.customer'] = $instance = new \PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CustomerGridDefinitionFactory(($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['prestashop.core.b2b.b2b_feature'] ?? $this->load('getPrestashop_Core_B2b_B2bFeatureService.php'))->isActive(), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\MultistoreFeature'] ?? $this->getMultistoreFeatureService())->isActive(), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->language->date_format_full, ($this->services['prestashop.adapter.feature.group_feature'] ?? $this->load('getPrestashop_Adapter_Feature_GroupFeatureService.php'))->isActive());

$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $instance;
