<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.grid_factory.store' shared service.

return $this->services['prestashop.core.grid.grid_factory.store'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(($this->services['PrestaShop\\PrestaShop\\Core\\Grid\\Definition\\Factory\\StoreGridDefinitionFactory'] ?? $this->load('getStoreGridDefinitionFactoryService.php')), new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\StoreGridDataFactory(($this->services['prestashop.core.grid.data.factory.store'] ?? $this->load('getPrestashop_Core_Grid_Data_Factory_StoreService.php'))), ($this->services['prestashop.core.grid.filter.form_factory'] ?? $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()));
