<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Product\ProductTypeType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\ProductTypeType'] = new \PrestaShopBundle\Form\Admin\Sell\Product\ProductTypeType(($this->services['prestashop.core.form.choice_provider.product_type_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ProductTypeChoiceProviderService.php')));
