<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.data_provider.customer_cart_decorator' shared service.

return $this->services['prestashop.core.grid.data_provider.customer_cart_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\CustomerCartGridDataFactoryDecorator(($this->services['prestashop.core.grid.data_provider.customer_cart'] ?? $this->load('getPrestashop_Core_Grid_DataProvider_CustomerCartService.php')), ($this->services['prestashop.core.localization.locale.context_locale'] ?? $this->load('getPrestashop_Core_Localization_Locale_ContextLocaleService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->currency->iso_code, ($this->services['prestashop.core.query_bus'] ?? $this->load('getPrestashop_Core_QueryBusService.php')));
