<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Address\RequiredFieldsAddressType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Address\\RequiredFieldsAddressType'] = new \PrestaShopBundle\Form\Admin\Sell\Address\RequiredFieldsAddressType(($this->services['prestashop.core.form.choice_provider.address_required_fields'] ?? ($this->services['prestashop.core.form.choice_provider.address_required_fields'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\AddressRequiredFieldsChoiceProvider())));
