<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Improve\International\Locations\StateType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Improve\\International\\Locations\\StateType'] = new \PrestaShopBundle\Form\Admin\Improve\International\Locations\StateType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.core.form.choice_provider.configurable_country_by_id'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ConfigurableCountryByIdService.php')), ($this->services['prestashop.core.form.choice_provider.zone_by_id'] ?? ($this->services['prestashop.core.form.choice_provider.zone_by_id'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\ZoneByIdChoiceProvider())));
