<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\SearchAndResetType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\SearchAndResetType'] = new \PrestaShopBundle\Form\Admin\Type\SearchAndResetType(($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')));
