<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Product\Pricing\SpecificPricePriorityType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Pricing\\SpecificPricePriorityType'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Pricing\SpecificPricePriorityType(($this->services['prestashop.core.form.choice_provider.specific_price_priority_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_SpecificPricePriorityChoiceProviderService.php')));
