<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Category\SimpleCategory' shared autowired service.

@trigger_error('The "PrestaShopBundle\\Form\\Admin\\Category\\SimpleCategory" service is deprecated. You should stop using it, as it will be removed in the future.', E_USER_DEPRECATED);

return $this->privates['PrestaShopBundle\\Form\\Admin\\Category\\SimpleCategory'] = new \PrestaShopBundle\Form\Admin\Category\SimpleCategory(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.data_provider.category'] ?? $this->load('getPrestashop_Adapter_DataProvider_CategoryService.php')));
