<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Improve\Design\MailTheme\TranslateMailsBodyType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Improve\\Design\\MailTheme\\TranslateMailsBodyType'] = new \PrestaShopBundle\Form\Admin\Improve\Design\MailTheme\TranslateMailsBodyType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages());
