<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Order\UpdateOrderShippingType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Order\\UpdateOrderShippingType'] = new \PrestaShopBundle\Form\Admin\Sell\Order\UpdateOrderShippingType(($this->services['prestashop.adapter.form.choice.provider.carrier_for_order_choice_provider'] ?? ($this->services['prestashop.adapter.form.choice.provider.carrier_for_order_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\CarrierForOrderChoiceProvider())));
