<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Product\Combination\CombinationImagesChoiceType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Combination\\CombinationImagesChoiceType'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Combination\CombinationImagesChoiceType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.core.form.choice_provider.product_images_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ProductImagesChoiceProviderService.php')));
