<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\ConfigurableCountryChoiceType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\ConfigurableCountryChoiceType'] = new \PrestaShopBundle\Form\Admin\Type\ConfigurableCountryChoiceType(($this->services['prestashop.core.form.choice_provider.configurable_country_by_id'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ConfigurableCountryByIdService.php')));
