<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\CartRule\EventListener\DiscountListener' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\CartRule\\EventListener\\DiscountListener'] = new \PrestaShopBundle\Form\Admin\Sell\CartRule\EventListener\DiscountListener(($this->privates['PrestaShop\\PrestaShop\\Core\\Form\\ChoiceProvider\\DiscountApplicationChoiceProvider'] ?? $this->load('getDiscountApplicationChoiceProviderService.php')), ($this->services['form.form_cloner'] ?? ($this->services['form.form_cloner'] = new \PrestaShopBundle\Form\FormCloner())));
