<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Adapter\CartRule\CommandHandler\EditCartRuleHandler' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Adapter\\CartRule\\CommandHandler\\EditCartRuleHandler'] = new \PrestaShop\PrestaShop\Adapter\CartRule\CommandHandler\EditCartRuleHandler(($this->privates['PrestaShop\\PrestaShop\\Adapter\\CartRule\\Repository\\CartRuleRepository'] ?? $this->load('getCartRuleRepositoryService.php')));
