<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\EmailType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\EmailType'] = new \PrestaShopBundle\Form\Admin\Type\EmailType(($this->services['prestashop.bundle.form.data_transformer.idn_converter'] ?? $this->load('getPrestashop_Bundle_Form_DataTransformer_IdnConverterService.php')));
