<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.extension.default_empty_data' shared autowired service.

return $this->services['form.extension.default_empty_data'] = new \PrestaShopBundle\Form\Extension\DefaultEmptyDataExtension();
