<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureRepository' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Adapter\\Feature\\Repository\\FeatureRepository'] = new \PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureRepository(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), 'ps_', ($this->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\Validate\\FeatureValidator'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\Validate\\FeatureValidator'] = new \PrestaShop\PrestaShop\Adapter\Feature\Validate\FeatureValidator())));
