<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Improve\Design\MailTheme\GenerateMailsType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Improve\\Design\\MailTheme\\GenerateMailsType'] = new \PrestaShopBundle\Form\Admin\Improve\Design\MailTheme\GenerateMailsType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['prestashop.core.form.choice_provider.mail_themes'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_MailThemesService.php'))->getChoices(), ($this->services['prestashop.core.form.choice_provider.theme_by_name_with_emails'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ThemeByNameWithEmailsService.php'))->getChoices());
