<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\GenderByIdChoiceProvider' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Form\\ChoiceProvider\\GenderByIdChoiceProvider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\GenderByIdChoiceProvider();
