<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\QueryHandler\GetApplicationForEditingHandler' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Domain\\AuthorizationServer\\QueryHandler\\GetApplicationForEditingHandler'] = new \PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\QueryHandler\GetApplicationForEditingHandler(($this->services['PrestaShopBundle\\Entity\\Repository\\AuthorizedApplicationRepository'] ?? $this->load('getAuthorizedApplicationRepositoryService.php')));
