<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Improve\Design\MailTheme\MailThemeConfigurationType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Improve\\Design\\MailTheme\\MailThemeConfigurationType'] = new \PrestaShopBundle\Form\Admin\Improve\Design\MailTheme\MailThemeConfigurationType(($this->services['prestashop.core.form.choice_provider.mail_themes'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_MailThemesService.php'))->getChoices());
