<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Configure\ShopParameters\TrafficSeo\Meta\MetaType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Configure\\ShopParameters\\TrafficSeo\\Meta\\MetaType'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\TrafficSeo\Meta\MetaType(($this->services['prestashop.core.form.choice_provider.default_meta_page_name'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_DefaultMetaPageNameService.php'))->getChoices(), ($this->services['prestashop.core.form.choice_provider.module_meta_page_name'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ModuleMetaPageNameService.php'))->getChoices(), ($this->services['translator'] ?? $this->getTranslatorService()));
