<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\AdvancedParameters\Performance\OptionalFeaturesType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\AdvancedParameters\\Performance\\OptionalFeaturesType'] = new \PrestaShopBundle\Form\Admin\AdvancedParameters\Performance\OptionalFeaturesType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.adapter.combination_feature'] ?? $this->load('getPrestashop_Adapter_CombinationFeatureService.php'))->isUsed());
