<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Product\ProductCustomField' shared autowired service.

@trigger_error('The "PrestaShopBundle\\Form\\Admin\\Product\\ProductCustomField" service is deprecated. You should stop using it, as it will be removed in the future.', E_USER_DEPRECATED);

return $this->privates['PrestaShopBundle\\Form\\Admin\\Product\\ProductCustomField'] = new \PrestaShopBundle\Form\Admin\Product\ProductCustomField(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService()));
