<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Customer\RequiredFieldsType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Customer\\RequiredFieldsType'] = new \PrestaShopBundle\Form\Admin\Sell\Customer\RequiredFieldsType(($this->services['prestashop.core.form.choice_provider.customer_required_fields'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_CustomerRequiredFieldsService.php'))->getChoices());
