<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\TaxInclusionChoiceType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\TaxInclusionChoiceType'] = new \PrestaShopBundle\Form\Admin\Type\TaxInclusionChoiceType(($this->services['prestashop.core.form.choice_provider.tax_inclusion'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_TaxInclusionService.php')));
