<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\TypeaheadCustomerCollectionType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\TypeaheadCustomerCollectionType'] = new \PrestaShopBundle\Form\Admin\Type\TypeaheadCustomerCollectionType(($this->services['prestashop.adapter.data_provider.customer'] ?? ($this->services['prestashop.adapter.data_provider.customer'] = new \PrestaShop\PrestaShop\Adapter\Customer\CustomerDataProvider())));
