<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuO/kLv1mdK0BsDLjZXqB'."\n".'lMbYRu9H1iDDWliRZnZGRcrQq6HCaydL06BXh5UW2rKWKH9ylDO+mpSH6CboJCsS'."\n".'A7FF68BoAHEwkt/6I2cASVSOQAQT+lk7IjKVUwbHM4TFX/UdcM425YXUKSxlWpKG'."\n".'hUXRYjqdHnAKyzwzOzf0POm8DO3tSKnk1gBKK+3+3Dw2tEix2Iw5l/og3WHzId++'."\n".'T7b7gGtn2O3oBSpBjpU6cLbt+LpE1IAb9i69NnphCMOJ0kvmZ9FnUkjtowUZa6I7'."\n".'fHS15va6+vn8/pRm8ciH23+0y4UYrs4Lk+LN4kuYW25gV6jWRlMLYQyi1w2now+C'."\n".'WQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
