<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\TaxRuleGridDataFactory' shared service.

return $this->services['PrestaShop\\PrestaShop\\Core\\Grid\\Data\\Factory\\TaxRuleGridDataFactory'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\TaxRuleGridDataFactory(($this->services['prestashop.core.grid.data.factory.tax_rule'] ?? $this->load('getPrestashop_Core_Grid_Data_Factory_TaxRuleService.php')), ($this->services['translator'] ?? $this->getTranslatorService()));
