<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Country\CommandHandler\AddCountryHandler' shared autowired service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Country\\CommandHandler\\AddCountryHandler'] = new \PrestaShop\PrestaShop\Adapter\Country\CommandHandler\AddCountryHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\Country\\Repository\\CountryRepository'] ?? $this->load('getCountryRepositoryService.php')));
