<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Adapter\Customer\Group\CommandHandler\AddCustomerGroupHandler' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Adapter\\Customer\\Group\\CommandHandler\\AddCustomerGroupHandler'] = new \PrestaShop\PrestaShop\Adapter\Customer\Group\CommandHandler\AddCustomerGroupHandler(new \PrestaShop\PrestaShop\Adapter\Customer\Group\Validate\CustomerGroupValidator(($this->services['PrestaShop\\PrestaShop\\Adapter\\Shop\\Repository\\ShopRepository'] ?? $this->load('getShopRepositoryService.php'))), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Customer\\Group\\Repository\\GroupRepository'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Customer\\Group\\Repository\\GroupRepository'] = new \PrestaShop\PrestaShop\Adapter\Customer\Group\Repository\GroupRepository())));
