<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Improve\Design\Theme\AdaptThemeToRTLLanguagesType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Improve\\Design\\Theme\\AdaptThemeToRTLLanguagesType'] = new \PrestaShopBundle\Form\Admin\Improve\Design\Theme\AdaptThemeToRTLLanguagesType(($this->services['prestashop.core.form.choice_provider.theme'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ThemeService.php'))->getChoices());
