<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Improve\International\Currencies\CurrencyExchangeRateType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Improve\\International\\Currencies\\CurrencyExchangeRateType'] = new \PrestaShopBundle\Form\Admin\Improve\International\Currencies\CurrencyExchangeRateType();
