<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Improve\Shipping\Preferences\CarrierOptionsType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Improve\\Shipping\\Preferences\\CarrierOptionsType'] = new \PrestaShopBundle\Form\Admin\Improve\Shipping\Preferences\CarrierOptionsType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.adapter.data_provider.carrier'] ?? $this->load('getPrestashop_Adapter_DataProvider_CarrierService.php'))->getActiveCarriersChoices(), ($this->services['prestashop.adapter.data_provider.carrier'] ?? $this->load('getPrestashop_Adapter_DataProvider_CarrierService.php'))->getOrderByChoices(), ($this->services['prestashop.adapter.data_provider.carrier'] ?? $this->load('getPrestashop_Adapter_DataProvider_CarrierService.php'))->getOrderWayChoices());
