<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\CurrencyChoiceType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\CurrencyChoiceType'] = new \PrestaShopBundle\Form\Admin\Type\CurrencyChoiceType(($this->services['PrestaShop\\PrestaShop\\Adapter\\Currency\\CurrencyDataProvider'] ?? $this->getCurrencyDataProviderService()), ($this->services['PrestaShop\\PrestaShop\\Core\\Form\\ChoiceProvider\\CurrencyByIdChoiceProvider'] ?? $this->load('getCurrencyByIdChoiceProviderService.php')));
