<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Category\DeleteCategoriesType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Category\\DeleteCategoriesType'] = new \PrestaShopBundle\Form\Admin\Sell\Category\DeleteCategoriesType(($this->services['prestashop.core.form.choice_provider.category_delete_mode'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_CategoryDeleteModeService.php'))->getChoices());
