<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Form\ChoiceProvider\DiscountApplicationChoiceProvider' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Form\\ChoiceProvider\\DiscountApplicationChoiceProvider'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\DiscountApplicationChoiceProvider(($this->services['translator'] ?? $this->getTranslatorService()));
