<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Customer\GroupType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Customer\\GroupType'] = new \PrestaShopBundle\Form\Admin\Sell\Customer\GroupType(($this->services['PrestaShop\\PrestaShop\\Adapter\\Form\\ChoiceProvider\\GroupByIdChoiceProvider'] ?? $this->load('getGroupByIdChoiceProviderService.php')));
