<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Customer\GenderType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Customer\\GenderType'] = new \PrestaShopBundle\Form\Admin\Sell\Customer\GenderType(($this->services['PrestaShop\\PrestaShop\\Adapter\\Form\\ChoiceProvider\\GenderByIdChoiceProvider'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Form\\ChoiceProvider\\GenderByIdChoiceProvider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\GenderByIdChoiceProvider())));
