<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\CustomerService\MerchandiseReturn\OrderReturnType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\CustomerService\\MerchandiseReturn\\OrderReturnType'] = new \PrestaShopBundle\Form\Admin\Sell\CustomerService\MerchandiseReturn\OrderReturnType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.adapter.form.choice_provider.order_return_state'] ?? $this->load('getPrestashop_Adapter_Form_ChoiceProvider_OrderReturnStateService.php'))->getChoices());
