<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Product\ProductOptions' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Product\\ProductOptions'] = new \PrestaShopBundle\Form\Admin\Product\ProductOptions(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService()), ($this->services['prestashop.adapter.data_provider.supplier'] ?? $this->load('getPrestashop_Adapter_DataProvider_SupplierService.php')), ($this->services['prestashop.adapter.data_provider.attachment'] ?? $this->load('getPrestashop_Adapter_DataProvider_AttachmentService.php')), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')));
