<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Feature\ProductFeature' shared autowired service.

@trigger_error('The "PrestaShopBundle\\Form\\Admin\\Feature\\ProductFeature" service is deprecated. You should stop using it, as it will be removed in the future.', E_USER_DEPRECATED);

return $this->privates['PrestaShopBundle\\Form\\Admin\\Feature\\ProductFeature'] = new \PrestaShopBundle\Form\Admin\Feature\ProductFeature(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService()), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')), ($this->services['prestashop.adapter.data_provider.feature'] ?? $this->load('getPrestashop_Adapter_DataProvider_FeatureService.php')));
