<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\PriceReductionType' shared autowired service.

$a = ($this->services['PrestaShop\\PrestaShop\\Adapter\\Currency\\CurrencyDataProvider'] ?? $this->getCurrencyDataProviderService());

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\PriceReductionType'] = new \PrestaShopBundle\Form\Admin\Type\PriceReductionType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['form.event_listener.price_reduction'] ?? $this->load('getForm_EventListener_PriceReductionService.php')), new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\ReductionTypeChoiceProvider($a), $a);
