<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\ShopChoiceTreeType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\ShopChoiceTreeType'] = new \PrestaShopBundle\Form\Admin\Type\ShopChoiceTreeType(($this->services['prestashop.adapter.form.choice_provider.shop_tree_choice_provider'] ?? ($this->services['prestashop.adapter.form.choice_provider.shop_tree_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\ShopTreeChoiceProvider())), ($this->services['prestashop.bundle.form.data_transformer.default_language_to_filled_array'] ?? $this->load('getPrestashop_Bundle_Form_DataTransformer_DefaultLanguageToFilledArrayService.php')), ($this->services['prestashop.adapter.shop.context'] ?? ($this->services['prestashop.adapter.shop.context'] = new \PrestaShop\PrestaShop\Adapter\Shop\Context())), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\MultistoreFeature'] ?? $this->getMultistoreFeatureService()));
