<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\TypeaheadProductPackCollectionType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\TypeaheadProductPackCollectionType'] = new \PrestaShopBundle\Form\Admin\Type\TypeaheadProductPackCollectionType();
