<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\CommandHandler\AddApplicationHandler' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Domain\\AuthorizationServer\\CommandHandler\\AddApplicationHandler'] = new \PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\CommandHandler\AddApplicationHandler(($this->services['PrestaShopBundle\\Entity\\Repository\\AuthorizedApplicationRepository'] ?? $this->load('getAuthorizedApplicationRepositoryService.php')), new \PrestaShopBundle\Model\AuthorizationServer\AuthorizedApplicationFactory());
