<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Product\Category\CategoryTreeSelectorType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Category\\CategoryTreeSelectorType'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Category\CategoryTreeSelectorType(($this->services['translator'] ?? $this->getTranslatorService()));
