<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Image\Uploader\CategoryImageUploader' shared autowired service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Image\\Uploader\\CategoryImageUploader'] = new \PrestaShop\PrestaShop\Adapter\Image\Uploader\CategoryImageUploader(($this->services['prestashop.adapter.image.uploader.category_cover_image_uploader'] ?? ($this->services['prestashop.adapter.image.uploader.category_cover_image_uploader'] = new \PrestaShop\PrestaShop\Adapter\Image\Uploader\CategoryCoverImageUploader())), ($this->services['prestashop.adapter.image.uploader.category_thumbnail_image_uploader'] ?? ($this->services['prestashop.adapter.image.uploader.category_thumbnail_image_uploader'] = new \PrestaShop\PrestaShop\Adapter\Image\Uploader\CategoryThumbnailImageUploader())), ($this->services['prestashop.adapter.image.uploader.category_menu_thumbnail_image_uploader'] ?? $this->load('getPrestashop_Adapter_Image_Uploader_CategoryMenuThumbnailImageUploaderService.php')));
