<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\CartRule\DiscountType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\CartRule\\DiscountType'] = new \PrestaShopBundle\Form\Admin\Sell\CartRule\DiscountType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\CartRule\\EventListener\\DiscountListener'] ?? $this->load('getDiscountListenerService.php')), ($this->privates['PrestaShop\\PrestaShop\\Core\\Form\\ChoiceProvider\\DiscountApplicationChoiceProvider'] ?? $this->load('getDiscountApplicationChoiceProviderService.php')));
