<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Email\EmailConfigurationType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Configure\\AdvancedParameters\\Email\\EmailConfigurationType'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Email\EmailConfigurationType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.core.form.choice_provider.mail_method'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_MailMethodService.php')), ($this->services['prestashop.core.form.choice_provider.contact_by_id'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ContactByIdService.php')));
