<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.extension.external_link' shared autowired service.

return $this->services['form.extension.external_link'] = new \PrestaShopBundle\Form\Extension\ExternalLinkExtension();
