<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.extension.disabling_switch_extension' shared autowired service.

return $this->services['form.extension.disabling_switch_extension'] = new \PrestaShopBundle\Form\Extension\DisablingSwitchExtension(($this->services['form.event_listener.add_disabling_switch_listener'] ?? $this->load('getForm_EventListener_AddDisablingSwitchListenerService.php')));
