<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\CustomerService\CustomerThread\ForwardCustomerThreadType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\CustomerService\\CustomerThread\\ForwardCustomerThreadType'] = new \PrestaShopBundle\Form\Admin\CustomerService\CustomerThread\ForwardCustomerThreadType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.form.choice_provider.employee_name_by_id'] ?? ($this->services['prestashop.adapter.form.choice_provider.employee_name_by_id'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\EmployeeNameByIdChoiceProvider())));
