<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Adapter\Alias\QueryHandler\GetAliasForEditingHandler' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Adapter\\Alias\\QueryHandler\\GetAliasForEditingHandler'] = new \PrestaShop\PrestaShop\Adapter\Alias\QueryHandler\GetAliasForEditingHandler(($this->privates['PrestaShop\\PrestaShop\\Adapter\\Alias\\Repository\\AliasRepository'] ?? $this->load('getAliasRepositoryService.php')));
