<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Category\Provider\MenuThumbnailAvailableKeyProvider' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Category\\Provider\\MenuThumbnailAvailableKeyProvider'] = new \PrestaShop\PrestaShop\Core\Category\Provider\MenuThumbnailAvailableKeyProvider(new \PrestaShop\PrestaShop\Core\Category\Provider\CategoryImageFinder((\dirname(__DIR__, 4).'/img/c/')));
