<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Product\ProductSpecificPrice' shared autowired service.

@trigger_error('The "PrestaShopBundle\\Form\\Admin\\Product\\ProductSpecificPrice" service is deprecated. You should stop using it, as it will be removed in the future.', E_USER_DEPRECATED);

return $this->privates['PrestaShopBundle\\Form\\Admin\\Product\\ProductSpecificPrice'] = new \PrestaShopBundle\Form\Admin\Product\ProductSpecificPrice(($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')), ($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.shop.context'] ?? ($this->services['prestashop.adapter.shop.context'] = new \PrestaShop\PrestaShop\Adapter\Shop\Context())), ($this->services['prestashop.adapter.data_provider.country'] ?? ($this->services['prestashop.adapter.data_provider.country'] = new \PrestaShop\PrestaShop\Adapter\Country\CountryDataProvider())), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Currency\\CurrencyDataProvider'] ?? $this->getCurrencyDataProviderService()), ($this->services['prestashop.adapter.data_provider.group'] ?? ($this->services['prestashop.adapter.data_provider.group'] = new \PrestaShop\PrestaShop\Adapter\Group\GroupDataProvider())), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService()), ($this->services['prestashop.adapter.data_provider.customer'] ?? ($this->services['prestashop.adapter.data_provider.customer'] = new \PrestaShop\PrestaShop\Adapter\Customer\CustomerDataProvider())));
