<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Type\Common\Team\ProfileChoiceType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Type\\Common\\Team\\ProfileChoiceType'] = new \PrestaShopBundle\Form\Admin\Type\Common\Team\ProfileChoiceType(($this->services['prestashop.adapter.form.choice_provider.profile_by_id_choice_provider'] ?? $this->load('getPrestashop_Adapter_Form_ChoiceProvider_ProfileByIdChoiceProviderService.php'))->getChoices());
