<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.factory.tax_rule' shared service.

$a = ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService());

$b = new \PrestaShop\PrestaShop\Core\Grid\Definition\Factory\TaxRuleGridDefinitionFactory($a);
$b->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $this->services['prestashop.core.grid.factory.tax_rule'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory($b, ($this->services['PrestaShop\\PrestaShop\\Core\\Grid\\Data\\Factory\\TaxRuleGridDataFactory'] ?? $this->load('getTaxRuleGridDataFactoryService.php')), ($this->services['prestashop.core.grid.filter.form_factory'] ?? $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')), $a);
