<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.domain.store.repository.store_repository' shared autowired service.

return $this->services['prestashop.core.domain.store.repository.store_repository'] = new \PrestaShop\PrestaShop\Core\Domain\Store\Repository\StoreRepository(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), 'ps_');
