<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Product\SEO\RedirectOptionType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\SEO\\RedirectOptionType'] = new \PrestaShopBundle\Form\Admin\Sell\Product\SEO\RedirectOptionType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')), new \PrestaShopBundle\Form\Admin\Sell\Product\DataTransformer\RedirectionTargetTransformer(), ($this->services['form.type.sell.product.event_listener.redirect_option_listener'] ?? ($this->services['form.type.sell.product.event_listener.redirect_option_listener'] = new \PrestaShopBundle\Form\Admin\Sell\Product\EventListener\RedirectOptionListener())), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getEmployeeLanguageIso(), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->getInt("PS_HOME_CATEGORY"));
