<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\SearchController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\Configure\\ShopParameters\\SearchController'] = $instance = new \PrestaShopBundle\Controller\Admin\Configure\ShopParameters\SearchController();

$instance->setContainer($this);

return $instance;
