<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqXswG/jrWukx0oP+n8ak'."\n".'fhTvjPQIruVfdXWEuK5P3DXXZCNfT+MFrWdrtDfiE1d0l9R84ReHcgj9/9hd0s55'."\n".'2FfI0lx9Xd0whTesLTzN36Huc1LWiLhhnOb/snhDh0tNCf6+6zluPXiPiljNwQHN'."\n".'F0bQsDOO9GDFjSB49LclrulwCHYk9IIYJGUXz7OGWMFT19LitNJKYcFf6PgNw5rG'."\n".'qbNML5tNWYS3Q5VX3g4PiSCmfpjNNFRnsaw8PxqN+heBB+QJl4CwO0oQS5HDurNo'."\n".'rScLMeVjHk2IkfOj8PsL0j6IWQ6C2JPGFPSCZymD7W/6PMg2Mk9JCyXEbMkoPOuN'."\n".'pQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
