<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Improve\International\Tax\TaxOptionsType' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Improve\\International\\Tax\\TaxOptionsType'] = new \PrestaShopBundle\Form\Admin\Improve\International\Tax\TaxOptionsType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->getBoolean("PS_USE_ECOTAX"), ($this->services['prestashop.core.form.choice_provider.tax_address_type_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_TaxAddressTypeChoiceProviderService.php')), ($this->services['prestashop.core.form.choice_provider.tax_rule_group_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_TaxRuleGroupChoiceProviderService.php')));
