<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Image\Uploader\TitleImageUploader' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Image\\Uploader\\TitleImageUploader'] = new \PrestaShop\PrestaShop\Adapter\Image\Uploader\TitleImageUploader();
