<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Title\Repository\TitleRepository' shared autowired service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Title\\Repository\\TitleRepository'] = new \PrestaShop\PrestaShop\Adapter\Title\Repository\TitleRepository(($this->services['PrestaShop\\PrestaShop\\Adapter\\Title\\Validate\\TitleValidator'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Title\\Validate\\TitleValidator'] = new \PrestaShop\PrestaShop\Adapter\Title\Validate\TitleValidator())));
