<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGMJu8dd\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGMJu8dd/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGMJu8dd.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGMJu8dd\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerGMJu8dd\appAppKernelDevDebugContainer([
    'container.build_hash' => 'GMJu8dd',
    'container.build_id' => '19ed5488',
    'container.build_time' => 1684437445,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGMJu8dd');
