<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSul9UMo\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSul9UMo/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSul9UMo.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSul9UMo\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerSul9UMo\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Sul9UMo',
    'container.build_id' => 'c10ddfdb',
    'container.build_time' => 1685374408,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSul9UMo');
